config/routes.rb
# == Route Map
#
#              Prefix Verb   URI Pattern                                       Controller#Action
#                root GET    /                                                 static_pages#home
#               about GET    /about(.:format)                                  static_pages#about
#             contact GET    /contact(.:format)                                static_pages#contact
#     inventor_robots GET    /inventors/:inventor_id/robots(.:format)          robots#index
#                     POST   /inventors/:inventor_id/robots(.:format)          robots#create
#  new_inventor_robot GET    /inventors/:inventor_id/robots/new(.:format)      robots#new
# edit_inventor_robot GET    /inventors/:inventor_id/robots/:id/edit(.:format) robots#edit
#      inventor_robot GET    /inventors/:inventor_id/robots/:id(.:format)      robots#show
#                     PATCH  /inventors/:inventor_id/robots/:id(.:format)      robots#update
#                     PUT    /inventors/:inventor_id/robots/:id(.:format)      robots#update
#                     DELETE /inventors/:inventor_id/robots/:id(.:format)      robots#destroy
#           inventors GET    /inventors(.:format)                              inventors#index
#                     POST   /inventors(.:format)                              inventors#create
#        new_inventor GET    /inventors/new(.:format)                          inventors#new
#       edit_inventor GET    /inventors/:id/edit(.:format)                     inventors#edit
#            inventor GET    /inventors/:id(.:format)                          inventors#show
#                     PATCH  /inventors/:id(.:format)                          inventors#update
#                     PUT    /inventors/:id(.:format)                          inventors#update
#                     DELETE /inventors/:id(.:format)                          inventors#destroy
#         robot_parts GET    /robots/:robot_id/parts(.:format)                 parts#index
#                     POST   /robots/:robot_id/parts(.:format)                 parts#create
#      new_robot_part GET    /robots/:robot_id/parts/new(.:format)             parts#new
#     edit_robot_part GET    /robots/:robot_id/parts/:id/edit(.:format)        parts#edit
#          robot_part GET    /robots/:robot_id/parts/:id(.:format)             parts#show
#                     PATCH  /robots/:robot_id/parts/:id(.:format)             parts#update
#                     PUT    /robots/:robot_id/parts/:id(.:format)             parts#update
#                     DELETE /robots/:robot_id/parts/:id(.:format)             parts#destroy
#

Rails.application.routes.draw do
  root 'static_pages#home'

  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  resources :inventors do
    resources :robots, except: [:index]
  end

  resources :robots, except: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :parts, except: [:show]
  end

end

app/models/part.rb
# == Schema Information
#
# Table name: parts
#
#  id         :integer          not null, primary key
#  name       :string
#  number     :integer
#  robot_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Part < ApplicationRecord
  belongs_to :robot
  validates :name, :number, presence: true
  validates :name, :number, uniqueness: true

  def self.by_name
    order(:name)
  end

end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_robot
  before_action :set_part, except: [:index, :new, :create]

  def index
    @parts = @robot.parts
  end

  def new
    @part = @robot.parts.new
  end

  def create
    @part = @robot.parts.new(part_params)
    if @part.save
      redirect_to robot_parts_path(@robot, @part)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @part.update(part_params)
      redirect_to robot_parts_path(@robot, @part)
    else
      render :edit
    end
  end

  def destroy
    @part.destroy
    redirect_to robot_parts_path(@robot, @part)
  end

  private
    def part_params
      params.require(:part).permit(:name, :number)
    end

    def set_robot
      @robot = Robot.find(params[:robot_id])
    end

    def set_part
      @part = @robot.parts.find(params[:id])
    end
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/parts/_form.html.erb
<%= form_for [@robot, @part] do |f| %>
  <div class="col m6">
    <%= f.label :name %>
    <%= f.text_field :name, required: true %>
  </div>
  <div class="col m6">
    <%= f.label :number %>
    <%= f.number_field :number %>
  </div>

  <%= f.submit class: "btn teal darken-3 white-text" %>
<% end %>

app/views/parts/edit.html.erb
<h1> Editing: <%= @robot.name %> </h1> 
<hr />

<%= render(partial: 'form') %>

app/views/parts/index.html.erb
<h1> Parts For Robot <%= @robot.name %> </h1>
<hr />

<% if @parts.any? %>
  <ul class="collapsible" data-collapsible="accordion">
    <% @parts.each do |part| %>
      <li>
        <div class="collapsible-header"><%= part.name %></div>
        <div class="collapsible-body">
          <p>Part: <%= part.number %></p>
           <%= link_to 'Edit', edit_robot_part_path(@robot, part), class: 'btn teal darken-3' %>
           <%= link_to 'Delete', robot_part_path(@robot, part), class: 'btn red accent-4',
            method: :delete, data: {confirm: 'Really Delete?'} %>
        </div>
      </li>
    <% end %>
  </ul>
<% else %>
  <h3> No Parts Found, Please Create One! </h3>
<% end %>

<%= link_to 'New Part', new_robot_part_path(@robot), class: 'btn teal darken-3' %>

app/views/parts/new.html.erb
<h1> New Part For <%= @robot.name %> </h1>
<hr />

<%= render(partial: 'form') %>