config/routes.rb
# == Route Map
#
#              Prefix Verb   URI Pattern                                       Controller#Action
#                root GET    /                                                 static_pages#home
#               about GET    /about(.:format)                                  static_pages#about
#             contact GET    /contact(.:format)                                static_pages#contact
#     inventor_robots GET    /inventors/:inventor_id/robots(.:format)          robots#index
#                     POST   /inventors/:inventor_id/robots(.:format)          robots#create
#  new_inventor_robot GET    /inventors/:inventor_id/robots/new(.:format)      robots#new
# edit_inventor_robot GET    /inventors/:inventor_id/robots/:id/edit(.:format) robots#edit
#      inventor_robot GET    /inventors/:inventor_id/robots/:id(.:format)      robots#show
#                     PATCH  /inventors/:inventor_id/robots/:id(.:format)      robots#update
#                     PUT    /inventors/:inventor_id/robots/:id(.:format)      robots#update
#                     DELETE /inventors/:inventor_id/robots/:id(.:format)      robots#destroy
#           inventors GET    /inventors(.:format)                              inventors#index
#                     POST   /inventors(.:format)                              inventors#create
#        new_inventor GET    /inventors/new(.:format)                          inventors#new
#       edit_inventor GET    /inventors/:id/edit(.:format)                     inventors#edit
#            inventor GET    /inventors/:id(.:format)                          inventors#show
#                     PATCH  /inventors/:id(.:format)                          inventors#update
#                     PUT    /inventors/:id(.:format)                          inventors#update
#                     DELETE /inventors/:id(.:format)                          inventors#destroy
#         robot_parts GET    /robots/:robot_id/parts(.:format)                 parts#index
#                     POST   /robots/:robot_id/parts(.:format)                 parts#create
#      new_robot_part GET    /robots/:robot_id/parts/new(.:format)             parts#new
#     edit_robot_part GET    /robots/:robot_id/parts/:id/edit(.:format)        parts#edit
#          robot_part GET    /robots/:robot_id/parts/:id(.:format)             parts#show
#                     PATCH  /robots/:robot_id/parts/:id(.:format)             parts#update
#                     PUT    /robots/:robot_id/parts/:id(.:format)             parts#update
#                     DELETE /robots/:robot_id/parts/:id(.:format)             parts#destroy
#

Rails.application.routes.draw do
  root 'static_pages#home'

  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  resources :inventors do
    resources :robots, except: [:index]
  end

  resources :robots, except: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :parts, except: [:show]
  end

end

app/models/robot.rb
# == Schema Information
#
# Table name: robots
#
#  id            :integer          not null, primary key
#  name          :string
#  serial_number :string
#  evil          :boolean
#  color         :string
#  industry      :string
#  inventor_id   :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Robot < ApplicationRecord
  has_many :parts, dependent: :destroy
  belongs_to :inventor
  validates :name, :serial_number, presence: true
  validates :name, :serial_number, uniqueness: true
  validates :industry, inclusion: {
    in: %w(education war service novelty),
    message: "Nope!"
  }, allow_nil: true


  def info
    if industry == 'education'
      "Education: #{name}, #{color}, #{serial_number}, #{industry}."
    elsif industry == 'war'
      "War: #{name}, #{color}, #{serial_number}, #{industry}."
    elsif industry == 'service'
      "Service: #{name}, #{color}, #{serial_number}, #{industry}."
    elsif industry == 'novelty'
      "Novelty: #{name}, #{color}, #{serial_number}, #{industry}."
    end
  end

  def self.by_name
    order(:name)
  end

  private
    def create_serial
      self.serial_number = '5'
    end

end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController
  before_action :set_inventor
  before_action :set_robot, except: [:index, :new, :create]

  def show
  end

  def new
    @robot = @inventor.robots.new
  end

  def create
    @robot = @inventor.robots.new(robot_params)
    if @robot.save
      redirect_to inventor_robot_path(@inventor, @robot)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @robot.update(robot_params)
      redirect_to inventor_robot_path(@inventor, @robot)
    else
      render :edit
    end
  end

  def destroy
    @robot.destroy
    redirect_to inventor_path(@inventor)
  end

  private
    def robot_params
      params.require(:robot).permit(:name, :evil, :serial_number, :color, :industry)
    end

    def set_inventor
      @inventor = Inventor.find(params[:inventor_id])
    end

    def set_robot
      @robot = @inventor.robots.find(params[:id])
    end
end

app/helpers/robots_helper.rb
module RobotsHelper
end

app/views/robots/_form.html.erb
<%= form_for [@inventor, @robot] do |f| %>
  <div class="col m6">
    <%= f.label :name %>
    <%= f.text_field :name, required: true %>
  </div>
  <div class="col m6">
    <%= f.label :serial_number %>
    <%= f.number_field :serial_number %>
  </div>
  <div class="col m6">
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>
  <div class="col m6">
    <%= f.label :industry %>
    <%= f.select :industry, ['education', 'war', 'service', 'novelty'] %>
  </div>
  <div class="input-field col s12">
    <%= f.label :evil %>
    <br />
    <%= f.select :evil, ['true', 'false'] %>
    <br />
  </div>

  <%= f.submit class: "btn teal darken-3 white-text" %>
<% end %>

app/views/robots/edit.html.erb
<h1> Editing Robot: <%= @robot.name %> </h1>
<hr />

<%= render(partial: 'form') %>

app/views/robots/new.html.erb
<h1> New Robot For: <%= @inventor.name %> </h1>
<hr />

<%= render(partial: 'form') %>

app/views/robots/show.html.erb
<div class='center'>
<h1> <%= @robot.name %> </h1>
<hr />

<% div_color = @robot.evil ? 'red' : 'green' %>

<div class="<%= div_color %> " >
  <i> Serial Number: <%= @robot.serial_number %> </i>
  <br />
  <strong> Evil: <%= @robot.evil ? 'Yes, Very!' : 'Nope!' %> </strong>
  <br />
  <strong> Color: <%= @robot.color %> </strong>
  <br />
  <strong> Industry: <%= @robot.industry %> </strong>
</div>

<br />

<div>
  <%= link_to 'Show Parts', robot_parts_path(@robot), class: 'btn teal darken-3' %>
</div>

<br />

<%= link_to "#{@inventor.name.pluralize} Robots", inventor_path(@inventor), class: 'btn teal darken-3' %>

</div>