config/routes.rb
# == Route Map
#
#              Prefix Verb   URI Pattern                                       Controller#Action
#                root GET    /                                                 static_pages#home
#               about GET    /about(.:format)                                  static_pages#about
#             contact GET    /contact(.:format)                                static_pages#contact
#     inventor_robots GET    /inventors/:inventor_id/robots(.:format)          robots#index
#                     POST   /inventors/:inventor_id/robots(.:format)          robots#create
#  new_inventor_robot GET    /inventors/:inventor_id/robots/new(.:format)      robots#new
# edit_inventor_robot GET    /inventors/:inventor_id/robots/:id/edit(.:format) robots#edit
#      inventor_robot GET    /inventors/:inventor_id/robots/:id(.:format)      robots#show
#                     PATCH  /inventors/:inventor_id/robots/:id(.:format)      robots#update
#                     PUT    /inventors/:inventor_id/robots/:id(.:format)      robots#update
#                     DELETE /inventors/:inventor_id/robots/:id(.:format)      robots#destroy
#           inventors GET    /inventors(.:format)                              inventors#index
#                     POST   /inventors(.:format)                              inventors#create
#        new_inventor GET    /inventors/new(.:format)                          inventors#new
#       edit_inventor GET    /inventors/:id/edit(.:format)                     inventors#edit
#            inventor GET    /inventors/:id(.:format)                          inventors#show
#                     PATCH  /inventors/:id(.:format)                          inventors#update
#                     PUT    /inventors/:id(.:format)                          inventors#update
#                     DELETE /inventors/:id(.:format)                          inventors#destroy
#         robot_parts GET    /robots/:robot_id/parts(.:format)                 parts#index
#                     POST   /robots/:robot_id/parts(.:format)                 parts#create
#      new_robot_part GET    /robots/:robot_id/parts/new(.:format)             parts#new
#     edit_robot_part GET    /robots/:robot_id/parts/:id/edit(.:format)        parts#edit
#          robot_part GET    /robots/:robot_id/parts/:id(.:format)             parts#show
#                     PATCH  /robots/:robot_id/parts/:id(.:format)             parts#update
#                     PUT    /robots/:robot_id/parts/:id(.:format)             parts#update
#                     DELETE /robots/:robot_id/parts/:id(.:format)             parts#destroy
#

Rails.application.routes.draw do
  root 'static_pages#home'

  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  resources :inventors do
    resources :robots, except: [:index]
  end

  resources :robots, except: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :parts, except: [:show]
  end

end

app/models/inventor.rb
# == Schema Information
#
# Table name: inventors
#
#  id         :integer          not null, primary key
#  name       :string
#  age        :integer
#  hire_date  :date
#  speciality :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Inventor < ApplicationRecord
  has_many :robots, dependent: :destroy
  # validates_presence_of :name, :hire_date same as below
  validates :name, :hire_date, presence: true
  validates :speciality, inclusion: { in: %w(software hardware education mad),
     message: "Not valid" }, allow_nil: true

  after_initialize :hire

  def info
    if speciality == 'software'
      "Software: #{name} was hired on: #{hire_date}."
    elsif speciality == 'hardware'
      "Hardware: #{name} was hired on: #{hire_date}."
    elsif speciality == 'education'
      "Education: #{name} was hired on: #{hire_date}."
    elsif speciality == 'mad'
      "Mad: #{name} was hired on: #{hire_date}."
    end
  end

  def self.by_name
    order(:name)
  end

  private
    def hire
      self.hire_date = Date.today
    end
end

app/controllers/inventors_controller.rb
class InventorsController < ApplicationController
  before_action :set_inventor, only: [:edit, :update, :show, :destroy]

  def index
    @inventors = Inventor.all
  end

  def show
    @robots = @inventor.robots
  end

  def new
    @inventor = Inventor.new
  end

  def create
    params[:inventor][:hire_date] = Date.today
    @inventor = Inventor.new(inventor_params)
    if @inventor.save
      redirect_to inventor_path(@inventor)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @inventor.update(inventor_params)
      redirect_to inventor_path(@inventor)
    else
      render :edit
    end
  end

  def destroy
    @inventor.destroy
    redirect_to inventors_path
  end

  private
    def inventor_params
      params.require(:inventor).permit(:name, :age, :hire_date, :speciality)
    end

    def set_inventor
      @inventor = Inventor.find(params[:id])
    end
end

app/helpers/inventors_helper.rb
module InventorsHelper
end

app/views/inventors/_form.html.erb
<%= form_for @inventor do |f| %>
  <div class="col m6">
    <%= f.label :name %>
    <%= f.text_field :name, required: true %>
  </div>
  <div class="col m6">
    <%= f.label :age %>
    <%= f.number_field :age, min: 18, max: 100 %>
  </div>
  <div class="input-field col s12">
      <%= f.label :speciality%>
      <br />
      <%= f.select :speciality, options_for_select(['software', 'hardware', 'education', 'mad']) %>
      <br />
  </div>
  <%= f.submit class: "btn teal darken-3 white-text" %>
<% end %>

app/views/inventors/edit.html.erb
<h1 class="center"> Editing <%= @inventor.name %> </h1>
<div class="container">
  <div class="row">
    <%= render(partial: 'form') %>
  </div>
</div>

app/views/inventors/index.html.erb
<h1 class="center"> Inventors </h1>
<div class="center">
  <%= link_to 'Add Inventor', new_inventor_path, class: "btn"  %>
</div>
<hr />
<ul class ="collection">
  <% @inventors.each do |inventor| %>
    <li class="collection-item">
      <%= link_to inventor.name, inventor_path(inventor) %>
    </li>
  <% end %>
</ul>

app/views/inventors/new.html.erb
<h1 class="center"> Hire an inventor </h1>
<div class="container">
  <div class="row">
    <%= render(partial: 'form') %>
  </div>
</div>

app/views/inventors/show.html.erb
<div class="row">
  <div class="col s12 center">
    <div class="card teal">
      <div class="card-content white-text">
        <span class="card-title"> Inventor: <%= @inventor.name %> </span>
        <p>Age: <%= @inventor.age %></p>
        <p>Hire Date: <%= @inventor.hire_date.strftime('%B %e, %Y') %></p>
        <p>Specialty: <%= @inventor.speciality.titleize %></p>
        <p>Number of Robots: <%= @robots.count %></p>
      </div>
      <div class="card-action">
        <%= link_to 'Edit', edit_inventor_path(@inventor), class: 'teal-text text-lighten-5' %>
        <%= link_to 'Delete', inventor_path(@inventor), class: 'teal-text text-lighten-5', method: :delete,
          data: {confirm: 'Really Delete?'} %>
      </div>
    </div>
    <% if @robots.any? %>
      <h5> All Robots </h4>
        <div class="row">
        <% @robots.each do |robot| %>
        <div class="col s12 m6 l4">
          <div class="card teal">
            <div class="card-content white-text">
              <span class="card-title"> <%= robot.name %> </span>
              <p> Industry: <%= robot.industry %> </p>
            </div>
            <div class="card-action">
              <%= link_to 'Show', inventor_robot_path(@inventor, robot), class: 'teal-text text-lighten-5' %>
              <%= link_to 'Edit', edit_inventor_robot_path(@inventor, robot), class: 'teal-text text-lighten-5' %>
              <%= link_to 'Delete', inventor_robot_path(@inventor, robot), class: 'teal-text text-lighten-5', method: :delete,
                data: {confirm: 'Really Delete?'} %>
            </div>
          </div>
        </div>
    <% end %>
  </div>
  <% end %>
      <%= link_to 'New Robot', new_inventor_robot_path(@inventor), class: 'btn teal darken-3' %>
  </div>
</div>